server:
  port: 6060

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kanban
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
    hibernate:
      ddl-auto: create-drop